promise("Testando...", 0.9)
//   .then((value) => console.log(`Valor: ${value}`))
//   .catch((error) => console.log(`Erro: ${error}`));